# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: node:6.10.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm install bower -g
          - npm run build.prod
          - echo "Everything is awesome!"