export const LANG_ES_ERRORCODE_TRANS = {
  'ErrInternalServer': 'Ocurrio un error de servidor.',
  'ErrUnexpected': 'Ocurrio un error inesperado.',
  'ErrUnknown': 'Ocurrio un error desconocido.',
  'ErrServerUnavailable': 'El servidor no se encuentra disponible.',
  'ErrUnauthorized': 'Debe estar autenticado para realizar la operación.',
  'ErrForbidden': 'No tiene permisos para realizar la operación.',
  'ErrorUserPasswordInvalid': 'El usuario o la contraseña no son válidos.',
  'ErrCashRegisterOpen': 'La caja ya se encuentra abierta.',
  'ErrCashRegisterClose': 'La caja ya se encuentra cerrada.',
  'ErrCashRegisterPointOfSaleNotFound': 'No se pudo obtener el punto de venta para la maquina en la cual se encuentra.',
  'ErrInvalidAmount': 'El importe no es válido. Ingrese un importe mayor o igual a 0 (cero)',
  'ErrCashRegisterOperationNotFound': 'La operación no es válida. Por favor, contáctese con el Administrador del Sistema.',
  'ErrCashRegisterNotSaved': 'Ocurrio un error intentando guardar la Caja. Por favor, contáctese con el Administrador del Sistema.',
  'ErrPointsOfSaleNotFound': 'No se encontraron puntos de venta',
  'ErrPointOfSaleNotFound': 'No se encontro el punto de venta',
  'ErrPointOfSaleHasNoCashRegister': 'El punto de venta no tiene una caja asociada',
  'ErrReportParamsNotValid': 'Los parametros utilizados no son válidos para realizar la operación.',
  'ErrReportParamsNotValidPointOfSale': 'El punto de venta del parametro no coincide con el de la maquina utilizada.',
  'ErrReceiptNotSaved': 'Ocurrio un error intentando guardar el Recibo. Por favor, contáctese con el Administrador del Sistema.',
  'ErrReceiptSellerNotFound': 'No se pudo obtener el vendedor logueado en nel sistema.',
  'ErrReceiptTicketNotFound': 'No se pudo obtener el ticket ingresado.',
  'ErrReceiptClientNotFound': 'No se pudo obtener el cliente ingresado.',
  'ErrReceiptCartNotFound': 'No se pudo obtener el carrito ingresado.',
  'ErrReceiptNotFound': 'No se pudo obtener el recibo ingresado.',
  'ErrReceiptPointOfSaleNotFound': 'No se pudo obtener el punto de venta para la maquina en la cual se encuentra.',
  'ErrReceiptNotDeleted': 'Ocurrio un error intentando eliminar el Recibo. Por favor, contáctese con el Administrador del Sistema.',
  'ErrReceiptCashRegisterIsNotOpened': 'No se puede realizar la operacion porque la caja no está abierta. ',
  'ErrInvalidOperation': 'No se puede realizar la operacion',
  'ErrCartPriceRecalcInvalidState': 'No se puede Recalcular el Precio en el Estado actual del Pedido.',
  'ErrCartAddSelectProduct': 'Seleccione el producto que desea agregar.',
  'ErrCartStateNotAllowed': 'No se tiene acceso para modificar este pedido.',
  'ErrCartExpressMandatory': 'Debe seleccionar un expreso.!',
  'ErrCartPaidNotVerified': 'Debe verificar el pago antes de pasar el pedido de estado',
  'ErrCartLocationRequired': 'Debe ingresar ubicación',
  'ErrCartUserNotBuyer': 'No esta habilitado el usuario como comprador',
  'ErrUnsubscripted': 'El usuario esta desuscripto para recibir correos',
  'ErrNoPhysicalProductFound': 'No se encontraron productos físicos',
  'ErrNoProductMovementsFound': 'No se encontraron movimientos para el producto',
  'ReassignCartAssigneeRequired': 'Seleccione el usuario',
  'ErrCartUserNotBuyerExpress': 'No esta habilitado el usuario como comprador express',
};
