// export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
  'page title': 'BlazarWeb',
  'application name': 'Blazar',
  'help': 'Ayuda',
  'name': 'Nombre',
  'surname': 'Apellido',
  'email': 'Email',
  'user': 'Usuario',
  'password': 'Contraseña',
  'remember me': 'Recuérdame',
  'out of': 'de',
  'login': 'Ingresar',
  'logout': 'Salir',
  'sign in with': 'Ingrese con',
  'forgot your password?': '¿Olvido su contraseña?',
  'dont have an account yet?': '¿Aún no tiene una cuenta?',
  'sign up': 'Registrese ahora',
  'is required': 'es requerido',
  'ErrorTitle': 'Error',
  'login or create account': 'Ingrese o cree una cuenta nueva',
  'menu': 'Menú',
  'description': 'Descripción',
  'category': 'Categoría',
  'tags': 'Etiquetas',
  'no available information': 'Información de %0 no disponible',
  'home': 'Inicio',
  'social logins': 'Login social',
  'has to be a valid email': 'email tiene que ser un email válido',
  'registration form': 'Formulario de Registracion',
  'register': 'Registrese',
  'no data available': 'No hay datos',
  'log detail': 'Detalle del Log',
  'close': 'Cerrar',
  'appLogId': 'Log Id',
  'applicationName': 'Aplicación',
  'url': 'Ruta',
  'message': 'Mensaje',
  'type': 'Tipo',
  'stackTrace': 'Stack Trace',
  'clientTimeStamp': 'Fecha Cliente',
  'serverTimeStamp': 'Fecha Servidor',
  'userAgent': 'Agente de Usuario',
  'userName': 'Nombre Usuario',
  'clientIpAddress': 'Direccion IP del Cliente',
  'jsonData': 'Información Adicional',
  'logs': 'Logs',
  'search': 'Buscar',
  'no data to display': 'No hay datos para mostrar',
  'total': 'Total',
  'cash register report': 'Reporte Estado Caja',
  'billing receipt report': 'Recibos',
  'point of sale': 'Punto de venta',
  'date from': 'Fecha desde',
  'date to': 'Fecha hasta',
  'operation': 'Operación',
  'date': 'Fecha',
  'voucher number': 'Comprobante',
  'amount': 'Importe',
  'cash amount': 'Importe Efectivo',
  'card amount': 'Importe Tarjeta',
  'check amount': 'Importe Cheque',
  'deposit amount': 'Importe Depósito',
  'amount inland': 'Imp. Interior',
  'amount express': 'Imp. Express',
  'admin': 'Admin',
  'apps': 'Apps',
  'dashboard': 'Dashboard',
  'state': 'Estado',
  'cashregister': 'Caja',
  'products': 'Productos',
  'open': 'Abrir',
  'z closure': 'Cierre Z',
  'open cash register': 'Abrir Caja',
  'close cash register': 'Cerrar Caja',
  'cash register opened with success': 'La caja se abrio con éxito',
  'cash register closed with success': 'La caja se cerro con éxito',
  'cash register check updated with success': 'La marca de verificación se actualizo con exito',
  'cash register updated with success': 'La caja se actualizo con exito',
  'attention': '¡Atención!',
  'if you wish to operate please close the cash register first': 'Si desea operar primero Cierre la caja.',
  'if you wish to operate please open the cash register first': 'Si desea operar primero Abra la caja.',
  'cancel': 'Cancelar',
  'save': 'Guardar',
  'cash register detail': 'Detalle de Caja',
  'cash register state': 'Estado de Caja',
  'report': 'Informe',
  'checker': 'Cajero',
  'cash register checker report': 'Listado de Cajas',
  'history': 'Historial',
  'view detail': 'Ver detalle',
  'opening date': 'Fecha Apertura',
  'closure date': 'Fecha Cierre',
  'yes': 'Si',
  'no': 'No',
  'all': 'Todos',
  'are you sure you want to mark the cash register as checked': 'Desea marcar la caja como verificada ?',
  'verified': 'Verificado',
  'validate': 'Validar',
  'remove verified': 'Quitar verificado',
  'are you sure you want to remove the checked mark': 'Desea quitar la marca de verificación ?',
  'cash register closing': 'Cierre de Caja',
  'cash register opening': 'Apertura de Caja',
  'edit description': 'Editar Descripción',
  'select': 'Seleccionar',
  'select point of sale': 'Seleccione un punto de venta',
  'select point of sale legend': 'No se pudo determinar el punto de venta, seleccione uno:',
  'total amount': 'Importe Total',
  'billing': 'Facturación',
  'receipt': 'Recibos',
  'seller': 'Vendedor',
  'sellers': 'Vendedores',
  'amount from': 'Importe Desde',
  'amount to': 'Importe Hasta',
  'create receipt': 'Crear Recibo',
  'client': 'Cliente',
  'ticket': 'Ticket',
  'cart': 'Pedido',
  'receipt created with success': 'Recibo creado exitosamente',
  'select a cart': 'Elegir un Pedido',
  'select carts': 'Elegir Pedidos',
  'province': 'Provincia',
  'select a ticket': 'Elegir un Ticket',
  'select tickets': 'Elegir Tickets',
  'do you want to print the receipt': 'Desea además imprimir el Recibo que acaba de crear ?',
  'receipt created': 'Recibo creado',
  'receipt updated': 'Recibo modificado',
  'print receipt': 'Imprimir Recibo',
  'delete receipt': 'Eliminar Recibo',
  'receipt deleted with success': 'Recibo eliminado exitosamente',
  'receipt updated with success': 'Recibo modificado exitosamente',
  'are you sure you want to delete the receipt': 'Desea eliminar el recibo seleccionado ?',
  'client number': 'Cliente',
  'select clients' : 'Elegir Clientes',
  'select a client' : 'Elegir un Cliente',
  'edit receipt': 'Modificar Recibo',
  'save receipt': 'Guardar Recibo',
  'no client': 'Sin cliente',
  'no ticket': 'Sin ticket',
  'no cart': 'Sin pedido',
  'register date': 'F. Envio',
  'state date': 'F. Estado',
  'location': 'Ubicación',
  'location|short': 'Ubic.',
  'assignee': 'Asignado',
  'by state': 'Por estado',
  'cart number': 'Nro',
  'no track number': 'No número de guia',
  'priority': 'Prioridad',
  'ranking': 'Ranking',
  'detail': 'Detalle',
  'reassign': 'Reasignar',
  'in the cart is working the user': 'En el pedido se encuentra trabajando el usuario',
  'are you sure you want to reassign anyway': 'Esta seguro que desea reasignarlo?',
  'carried from point of sale': 'Retirar por local',
  'carried by shipping': 'Recibir por expreso',
  'working': 'Trabajando',
  'cart by state': 'Pedidos por estado',
  'group by state': 'Grupos por estado',
  'filter': 'Filtro',
  'payment|short': 'Pag.',
  'attached|short': 'Agr.',
  'paid': 'Pago',
  'cash on delivery': 'Contra reembolso',
  'has basket': 'Tiene canasto',
  'has cart attached': 'Tiene pedido anexo',
  'claim payment': 'Reclamar pago',
  'name and lastname': 'Nombre y apellido',
  'cuit': 'CUIT',
  'client address': 'Domicilio cliente',
  'iva': 'IVA',
  'debt': 'Deuda',
  'debt comment': 'Comentario deuda',
  'country': 'Pais',
  'city': 'Localidad',
  'shipping address': 'Domicilio de entrega',
  'express': 'Expreso',
  'track number': 'Número de guía',
  'shipping method': 'Método de envío',
  'Do you wish Besol to suggest you alternative products when there is no stock?':
      'Desea que Besol sugiera productos alternativos en caso que no tenga stock?',
  'cart detail': 'Detalle de Pedido',
  'phone': 'Teléfono',
  'comment': 'Comentario',
  'additional data': 'Información adicional',
  'internal data': 'Información interna',
  'not assigned': 'Sin asignar',
  'request addition': 'Solicitar agregado',
  'carry date': 'Fecha de retiro',
  'carry by': 'Persona que retirará',
  'paid checked': 'Verificación del pago',
  'delivery option': 'Forma de entrega',
  'deliver at door': 'Entrega a puerta',
  'deliver to subsidiary': 'Entrega a sucursal',
  'cart nro': 'Pedido N°',
  'pay cash on delivery': 'Pago contraembolso',
  'add': 'Agregar',
  'cart amount': 'Importe pedido',
  'shipping cost': 'Gasto de envío',
  'cart comment added with success': 'El comentario se agregó con éxito',
  'cart updated success' : 'El carrito fue actualizado correctamente.',
  'add product': 'Agregar Artículo',
  'recalculate price': 'Recalcular Precios',
  'change shippingAddress': 'Modificar dirección de entrega',
  'ok': 'Aceptar',
  'cart address updated with success': 'La dirección de entrega se modificó con éxito',
  'export': 'Descargar',
  'export excel': 'Descargar excel',
  'export pdf': 'Descargar pdf',
  'export attached pdf': 'Descargar agregado pdf',
  'export attached excel': 'Descargar agregado excel',
  'export attached': 'Descargar agregado',
  'locked|short': 'Bloq.',
  'confirmed|short': 'Conf.',
  'quantity|short': 'Cant.',
  'article|short': 'Art.',
  'unit price|short': 'Pcio. Unit.',
  'brand': 'Marca',
  'color': 'Color',
  'size': 'Talle',
  'option': 'Opción',
  'stock': 'Stock',
  'go back': 'Volver',
  'product added': 'Producto agregado',
  'number|short': 'Nro.',
  'bank': 'Banco',
  'transaction': 'Transacción',
  'approved': 'Aprobado',
  'rejected': 'Rechazado',
  'packaging': 'Embalaje',
  'weight': 'Peso',
  'delete': 'Eliminar',
  'add box': 'Agregar caja',
  'cancel cart': 'Cancelar Pedido',
  'reason': 'Motivo',
  'cart express updated with success': 'El pedido se modificó con éxito',
  'missing stock': 'Faltante de Stock',
  'missing stock hint': 'El stock para este pedido es insuficiente. Por favor corrigalo para poder pasarlo al estado armado.',
  'fix stock': 'Ajustar Stock',
  'print': 'Imprimir',
  'missing': 'Faltante',
  'settings': 'Configuración',
  'computer settings': 'Para esta computadora',
  'list page size': 'Tamaño de página',
  'change state': 'Cambiar estado',
  'article': 'Artículo',
  'offert': 'Oferta',
  'unit price': 'Precio Unitario',
  'quantity': 'Cantidad',
  'add article': 'Agregar Artículo',
  'cart paid check updated with success': 'El pedido se modificó con éxito',
  'addition requested with success': 'El mensaje se envió con éxito',
  'client stats': 'Datos del cliente',
  'last access': 'Fecha Ult. Acceso',
  'last access|short': 'U. Acceso',
  'current debt': 'Deuda actual',
  'registering date': 'Fecha de Registración',
  'registering date|short': 'F. Reg',
  'address': 'Dirección',
  'payments': 'Pagos',
  'carts': 'Pedidos',
  'product movements': 'Movimientos del producto',
  'physical products': 'Productos físicos',
  'outcome': 'Egreso',
  'income': 'Ingreso',
  'employee performance': 'Desempeño Vendedores',
  'by cart quantity': 'Por cantidad de pedidos',
  'by total amount': 'Por importe total',
  'by product quantity': 'Por cantidad de productos',
  'group': 'Grupo',
  'reassign cart': 'Reasignar Pedido',
  'assign': 'Asignar',
  'current assignee': 'Asignado al Usuario',
  'new assignee': 'Asignar al Usuario',
  'mail': 'Mail',
  'payment claims': 'Reclamos de Pago',
  'confirm send claim': 'Reclamar Pago',
  'do you wish to send a payment claim to this client': 'Desea enviarle un reclamo a este cliente',
  'by inactive users': 'Por no compradores',
  'operations': 'Operaciones',
  'new state': 'Nuevo Estado',
  'suppliers': 'Proveedores',
  'calendar': 'Calendario',
  'month': 'Mes',
  'week': 'Semana',
  'day': 'Día',
  'availability': 'Disponibilidad',
  'availability saved with success': 'Se guardó con exito',
  'available': 'Disponible',
  'from': 'Desde',
  'to': 'Hasta',
  'do you want to delete availability': 'Desea eliminar la disponibilidad de %0 a %1 Hs?',
  'delete availability': 'Eliminar disponibilidad',
  'available from to': 'Disponible de %0 a %1 Hs',
  'mon': 'Lun',
  'tue': 'Mar',
  'wed': 'Mie',
  'thu': 'Jue',
  'fri': 'Vie',
  'sat': 'Sab',
  'add recurrent': 'Agregar Recurrente',
  'generate': 'Generar Disponibilidad',
  'hour from': 'Hora desde',
  'hour to': 'Hora hasta',
  'dayRequired': 'Seleccione al menos un día',
  'dateEndRequired': 'Ingrese la fecha hasta',
  'badDateRange': 'Fecha hasta debe ser mayor a fecha desde',
  'badHourRange': 'Hora hasta debe ser mayor a fecha desde',
  'parameter': 'Parámetro',
  'parameters': 'Parámetros',
  'key': 'Clave',
  'value': 'Valor',
  'banners': 'Banners',
  'edit': 'Modificar',
  'Path': 'Nombre de archivo',
  'title': 'Título',
  'subtitle': 'Subtítulo',
  'positionX': 'Posición X',
  'positionY': 'Posición Y',
  'align left': '¿Alineado a la izquierda?',
  'widthSubtitle': 'Ancho de subtítulo',
  'banner update': 'Se modificó el orden de los banners',
  'banner error update': 'Error al modificar el orden de los banners',
  'banner_delete': 'Eliminar Banner',
  'are you sure delete banner?': '¿Está seguro que desea eliminar el banner?',
  'banner delete': 'Se eliminó el banner',
  'banner error delete': 'Error al eliminar el banner',
  'banner_edit': 'Modificar Banner',
  'banner_create': 'Agregar Banner',
  'banner edit': 'Se modificó el banner',
  'banner error edit': 'Error al modificar el banner',
  'banner add': 'Se agregó el banner',
  'banner error add': 'Error al agregar el banner',
  'imagenPath invalid': 'Nombre inválido',
  'banner error get': 'Error al obtener los banners',
  'Clean': 'Limpiar',
  'news': 'Novedades',
  'new_delete': 'Eliminar Novedad',
  'are you sure delete new?': '¿Está seguro que desea eliminar la novedad?',
  'new delete': 'Se eliminó la novedad',
  'new error delete': 'Error al eliminar la novedad',
  'new_edit': 'Modificar Novedad',
  'new_create': 'Agregar Novedad',
  'new edit': 'Se modificó la novedad',
  'new error edit': 'Error al modificar la novedad',
  'new add': 'Se agregó la novedad',
  'new error add': 'Error al agregar la novedad',
  'userState|short': 'Est. Usuario',
  'BuyerExpress': 'Comprador Express',
  'BuyerExpress|short': 'CE.',
  'Buyer': 'Comprador',
  'Buyer|short': 'C.',
  'Forbidden': 'No Comprador',
  'only buyer': 'Solo Compradores',
  'only active': 'Solo Activos',
  'show only no buyer': 'Mostrar solo no compradores',
  'show only no active': 'Mostrar solo no activos',
  'add user': 'Agregar usuario',
  'add group': 'Agregar Grupo',
  'are you sure add group express': '¿Desea agregar el grupo Comprador Express al Usuario?',
  'are you sure add group buyer': '¿Desea agregar el grupo Comprador al Usuario?',
  'are you sure start preparation on order':'¿Desea comenzar la preparación del pedido seleccionado?',
  'are you sure release order':'¿Desea soltar el pedido seleccionado?',
  'security': 'Seguridad',
  'security user': 'Adm. de usuarios',
  'security group': 'Adm. de grupos',
  'active': 'Activo',
  'active|short': 'A.',
  'inactive': 'Inactivo',
  'penalize|short': 'S.',
  'penalize': 'Sancionado',
  'catalogGroupAssigned|short': 'Catálogo asign.',
  'catalogGroupAssigned': 'Grupo catálogo asignado',
  'update key' : 'Cambiar clave',
  'group assign': 'Asignar al usuario',
  'user activate title' : 'Estado del usuario',
  'user activate message': '¿Realmente quieres activar el siguiente usuario?',
  'user deactivate message': '¿Realmente quieres desactivar el siguiente usuario?',
  'user add buyer group message': '¿Realmente quieres agregar al grupo comprador el siguiente usuario?',
  'user remove buyer group message': '¿Realmente quieres quitar el grupo comprador al siguiente usuario?',
  'user add buyer express group message': '¿Realmente quieres agregar al grupo comprador express el siguiente usuario?',
  'user remove group buyer express message': '¿Realmente quieres quitar el grupo comprador express al siguiente usuario?',
  'user add catalog group message': '¿Realmente quieres agregar el grupo catálogo el siguiente usuario?',
  'user remove catalog group message': '¿Realmente quieres quitar el grupo catálogo al siguiente usuario?',
  'user remove group message': '¿Realmente quieres quitar el siguiente usuario del grupo?',
  'newpassword': 'Nueva clave',
  'repeat new password': 'Repetir nueva clave',
  'needs at least': 'necesita al menos',
  'characters': 'caracteres',
  'change password': 'Actualizar contraseña',
  'password updated with success': 'Contraseña actualizada con exito',
  'the fields must be equals': 'Los campos deben ser iguales',
  'needs at least one number and one letter': 'Necesita al menos una letra y un número',
  'dni': 'Dni',
  'cp': 'CP',
  'howToContact': 'Como nos contactamos',
  'fax': 'Fax',
  'priceList': 'priceList',
  'businessName': 'Razon Social',
  'genre': 'Sexo',
  'woman': 'Mujer',
  'man': 'Hombre',
  'mobilePhone': 'Celular',
  'delivery': 'entrega',
  'fiscal': 'fiscal',
  'group created with success': 'Grupo creado con exito',
  'group details updated with success': 'Información del grupo actualizada con exito',
  'user detail': 'Detalles del usuario',
  'user details updated with success': 'Información de usuario actualizada con exito',
  'Cuit field is required': 'El campo Cuit es requerido',
  'Name field is required': 'El campo Nombre es requerido',
  'Surname field is required': 'El campo Apellido es requerido',
  'Email field is required': 'El campo Email es requerido',
  'DNI field is required': 'El campo DNI es requerido',
  'Birthday field is required': 'Ingrese una Fecha de nacimiento valida',
  'Phone field is required': 'El campo Teléfono es requerido',
  'Address field is required': 'Ingrese una domicilio personal valido',
  'City field is required': 'El campo Ciudad es requerido',
  'Iva field is required': 'El campo IVA es requerido',
  'Province is required': 'Provincia es requerido',
  'City is required': 'Localidad es requerido',
  'Tax province is required': 'Provincia fiscal es requerido',
  'Tax city is required': 'Localidad fiscal es requerido',
  'Tax address is required': 'Domicilio fiscal es requerido',
  'Business field is required': 'El campo Razon Social es requerido',
  'Debt': 'Deudas',
  'sale list': 'Lista de precios',
  'billInformation': 'Facturación',
  'clientinformation': 'Información del cliente',
  'deliveryInformation': 'Envío',
  'comments': 'Comentarios',
  'options': 'Otras opciones',
  'user group remove group revert message': '¿Realmente quieres mantener el siguiente usuario en el grupo?',
  'group not empty': 'No se puede eliminar un grupo si tiene vendedores o usuarios asignados',
  'group delete message': '¿Realmente quieres eliminar el siguiente grupo?',
  'group detail': 'Detalle de grupo',
  'users assigned' : 'Usuarios asignados',
  'no sellers assigned': 'Sin vendedores asignados',
  'purchases': 'Compras',
  'purchase order': 'Orden de Compra',
  'purchase order number': 'Nro. OC',
  'store': 'Local',
  'requested products': 'Prod. pedidos',
  'received products': 'Prod. recibidos',
  'delivered': 'Entregado',
  'pending delivery': 'Pendiente de entrega',
  'read': 'Leído',
  'filter by': 'Filtrar por',
  'new order': 'Nueva Orden',
  'total order': 'Total del Pedido',
  'min stock': "Stock Mínimo",
  'sold': 'Vendidos',
  'colour': 'Color',
  'code': 'Código',
  'finish order': 'TERMINAR PEDIDO',
  'undefined': 'No definida',
  'invalid data range': 'Rango de fechas inválido',
  'return': 'Volver',
  'send': 'Enviar',
  'select auto': 'Seleccionar automáticamente',
  'unselect all': 'Deseleccionar todos',
  'select all': 'Seleccionar todos',
  'assigned':'Asignados a mí',
  'release order':'Soltar pedido',
  'start preparation':'Comenzar preparación',
  'get order':'Obtener pedido',
  'successful operation':'Operación exitosa',
  'in cartState by vendorMail':'En %0 por: %1',
  'minimums':'Minimos',
  'download excel':'Descargar Excel',
  'load excel':'Cargar Excel',
  'save changes':'Guardar cambios',
  'upload the file':'Subí el archivo',
  'are u working at the brand':'Estás trabajando en la marca %0, subí el excel modificado de los mismos',
  'drag and drop the file':'Arrastrá el archivo o hacé click para buscar el archivo',
  'only one file at time allow':'Sólo podés subir un archivo a la vez',
  'delete file':'Eliminar archivo',
  'upload and update':'Subir y actualizar',
  'file must be .xlsx':'El archivo debe tener extensión .xlsx',
  'list':'Listado de Precios',
  'price-list-error':'Debe subir ListaDePrecios.pdf o ListaDePrecios.xls'
};
